### ISSUE TITLE
Potential error starting up? (Probably just me)

### ISSUE THREAD

**Issue by ZASMan** [OctoConsulting/engager#89]
Hey @dstepp, I was trying to take a look to see what you all are working on... I opened up `localhost:8080` on my browser and got this screen. I'm assuming this is part of the app? Clicking on the colors do nothing:

<img width="1278" alt="screen shot 2017-07-10 at 10 44 39 am" src="https://user-images.githubusercontent.com/13513340/28023925-4a904638-655d-11e7-89f5-0b76e1db8373.png">

 I'm not too experienced with node but I got some errors when I started up... I followed the directions of:

1. Running `npm update -g` to update npm on my machine globally.
2. Cloning the repo.
3. CDing into the directory and running `npm install`
4. CDing into the directory and running `brew services start mongodb`
5. CDing into engager and running `npm run dev`.
6. Opening up another terminal and CDing into engager and running `npm start.`

<img width="1279" alt="screen shot 2017-07-10 at 10 42 35 am" src="https://user-images.githubusercontent.com/13513340/28023948-5b69685e-655d-11e7-9d0b-adeeafd549cc.png">
<img width="1275" alt="screen shot 2017-07-10 at 10 42 24 am" src="https://user-images.githubusercontent.com/13513340/28023955-5f0e9cfe-655d-11e7-8e8f-0072c1aab4c9.png">

Otherwise, this is all the concepts and what it seems to be so far seems like a really fun/useful tool for Octo! Great work all!

**Comment by trandrew08** [comment]
Sorry we took the config file out of the repo because it has credentials for our APIs. We will specify in the README that we can send it out to people if they wanna fork it. We'll also put in a blank config file so it won't error out.

**Comment by ZASMan** [comment]
Not a problem at all! I can check it out another time. Thanks for letting me know. Keep up the good work!
